services:
  - type: web
    name: signlearn
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MODEL_PATH
        value: models/train18.h5
    plan: free
